// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: authors.sql

package query

import (
	"context"
)

const getAllAuthor = `-- name: GetAllAuthor :many
select id, first_name, last_name, email, birthdate, added from authors
`

func (q *Queries) GetAllAuthor(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, getAllAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Birthdate,
			&i.Added,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
