// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package query

import (
	"time"
)

type Author struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	Birthdate time.Time
	Added     time.Time
}

type Post struct {
	ID          int32
	AuthorID    int32
	Title       string
	Description string
	Content     string
	Date        time.Time
}
